---
require: rubocop-rake
AllCops:
  NewCops: enable
  TargetRubyVersion: 3.1
  DisplayCopNames: true
  Exclude:
    - "**/node_modules/**/*"
    - "**/target/**/*"
    - "**/vendor/**/*"
Layout/EndOfLine:
  EnforcedStyle: lf
Layout/LineLength:
  Enabled: true
  Exclude:
    - "scripts/gen_case_lookups.rb"
    - "**/Rakefile"
Metrics:
  Enabled: false
Style/Documentation:
  Enabled: false
